/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestMarks;
import javax.swing.*;
public class App {
    

    public static void main(String[] args) {
        
        SwingUtilities.invokeLater(()->{
        
        String studentNumber = JOptionPane.showInputDialog("Enter Student Number");
        String name = JOptionPane.showInputDialog("Enter Name");
        String surname = JOptionPane.showInputDialog("Enter Surname");
        String email = JOptionPane.showInputDialog("Enter Email");
        String phoneNumber = JOptionPane.showInputDialog("Enter Phone Number");
        int mark1 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 1"));
        int mark2 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 2"));
        int AssignmentMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Assignment Mark"));
        int examMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Exam Mark"));
        
        //Calculate DP Status
        boolean dpStatus = ((mark1 + mark2 + AssignmentMark) /3) >= 40;
        
        //Calculate The Final mark
        
        double courseWorkAverage = (mark1 + mark2 + AssignmentMark) / 3;
        double finalMark = (courseWorkAverage * 0.4) + (examMark * 0.6);
        String showPass;
        String myMessage;
        
        if(finalMark >= 0 && finalMark <= 46){
            showPass = "Failed";
            myMessage = finalMark + " You Have " + showPass;
            JOptionPane.showMessageDialog(null,myMessage);
        }else if(finalMark >= 47 && finalMark <= 49){
            showPass = "Support";
            myMessage = finalMark + " You Have " + showPass;
            JOptionPane.showMessageDialog(null,myMessage);
        }else if(finalMark >= 50 && finalMark <= 74){
            showPass = "Passed";
            myMessage = finalMark + " You Have " + showPass;
            JOptionPane.showMessageDialog(null,myMessage);
        }else{
            showPass = "Distinction";
            myMessage = finalMark + " You Have " + showPass;
            JOptionPane.showMessageDialog(null,myMessage);
        }
        
        //Display results
        
        String message = "Student Number: " + studentNumber + "\n"
                + "Name: " + name + " " + surname + "\n"
                + "Email: " + email + "\n"
                + "Phone Number: " + phoneNumber + "\n"
                + "Mark One: " +  mark1 + "\n"
                + "mark Two: " + mark2 + "\n"
                + "Assignment Mark: " + AssignmentMark + "\n"
                + "Dp Status: " + (dpStatus ? "Achieved" : "Not Achieved") + "\n"
                + "Grade: " + "You Have " + showPass + "\n"
                + "Final Mark: " + finalMark;
        
        JOptionPane.showMessageDialog(null, message);
    });
        
    }
}
